# Generated by Django 4.2 on 2023-04-25 19:00

import autoslug.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_livingoptions_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("AC", "AC"), ("3BR", "3 Bedroom"), ("AREA", "Area")],
                        max_length=255,
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, null=True, populate_from="name", unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "image",
                    models.ImageField(
                        max_length=500,
                        upload_to="living_options/images",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "webp"]
                            )
                        ],
                    ),
                ),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateField(auto_now=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, null=True, populate_from="name", unique=True
                    ),
                ),
                ("categories", models.ManyToManyField(to="app.category")),
            ],
        ),
    ]
