# Generated by Django 4.2 on 2023-04-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_category_house"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("Learning disabilities", "Learning disabilities"),
                    ("Autism", "Autism"),
                    ("Physical disabilities", "Physical disabilities"),
                    ("Acquired brain injuries", "Acquired brain injuries"),
                    ("Mental health", "Mental health"),
                    ("Homelessness", "Homelessness"),
                    ("Young People", "Young People"),
                ],
                max_length=255,
            ),
        ),
    ]
