# Generated by Django 4.2 on 2023-04-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_category_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="house",
            name="price",
        ),
        migrations.AddField(
            model_name="house",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
