# Generated by Django 4.2 on 2023-04-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_house_price_house_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="phone_number",
            field=models.CharField(default=2349137104825, max_length=20),
            preserve_default=False,
        ),
    ]
