# Generated by Django 4.2 on 2023-04-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_livingoptionscategory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livingoptions",
            name="title",
            field=models.CharField(
                choices=[
                    ("Learning disabilities", "Learning disabilities"),
                    ("Autism", "Autism"),
                    ("Physical disabilities", "Physical disabilities"),
                    ("Acquired brain injuries", "Acquired brain injuries"),
                    ("Mental health", "Mental health"),
                    ("Homelessness", "Homelessness"),
                    ("Young People", "Young People"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="livingoptionscategory",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
