# Generated by Django 4.2 on 2023-04-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_livingoptions_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livingoptions",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
