# Generated by Django 4.2 on 2023-05-09 14:24

import autoslug.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_category_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        max_length=500,
                        upload_to="careers/images",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "webp"]
                            )
                        ],
                    ),
                ),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateField(auto_now=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, null=True, populate_from="name", unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Career",
                "verbose_name_plural": "Careers",
            },
        ),
        migrations.AlterField(
            model_name="house",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="livingoptions",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
